"""your message

Revision ID: 7a92aa1c3431
Revises: 856b5d487f16
Create Date: 2025-02-05 18:10:53.176493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a92aa1c3431'
down_revision = '856b5d487f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
